In [2]:
import pandas as pd

In [4]:
stations_df = pd.read_csv("./database/canadian_stations.csv")
display(stations_df.head(10))

,province,station_name,icao,iata,synop,latitude,longitude,elevation_m,metar,nexrad,aviation,upper_air,auto_type,office_type,country
0,AB,ABEE AGDM,CXAF,NaN,7128.0,54 17,112 58W,664,Yes,NaN,NaN,NaN,NaN,NaN,CA
1,AB,ANDREW AGDM,CXAG,NaN,7128.0,53 55,112 17W,625,Yes,NaN,NaN,NaN,NaN,NaN,CA
2,AB,ATMORE AGDM,CXAJ,NaN,7128.0,54 46,112 49W,574,Yes,NaN,NaN,NaN,NaN,NaN,CA
3,AB,BANFF (MARS),CWZG,WZG,NaN,51 12,115 32W,397,Yes,NaN,NaN,NaN,NaN,NaN,CA
4,AB,BARNWELL AGDM,CXBW,NaN,7134.0,49 48,112 18W,824,Yes,NaN,NaN,NaN,NaN,NaN,CA
5,AB,BEAVERLODGE,CWBM,NaN,7123.0,55 12,119 24W,745,Yes,NaN,NaN,NaN,NaN,NaN,CA
6,AB,BODO AGDM,CXBA,NaN,7121.0,52 07,110 06W,687,Yes,NaN,NaN,NaN,NaN,NaN,CA
7,AB,BOW ISLAND,CWXL,WXL,7123.0,49 44,111 27W,817,Yes,NaN,NaN,NaN,NaN,NaN,CA
8,AB,BOW VALLEY,CWXA,WXA,7123.0,51 04,115 04W,298,Yes,NaN,NaN,NaN,NaN,NaN,CA
9,AB,BROCKET AGDM,CXBR,NaN,7134.0,49 37,113 49W,73,Yes,NaN,NaN,NaN,NaN,NaN,CA

In [ ]:
# get all rows that metar and taf both are available
available_stations_df = stations_df[(stations_df['metar'] == "Yes")&(stations_df['aviation'])]
display(available_stations_df)

,province,station_name,icao,iata,synop,latitude,longitude,elevation_m,metar,nexrad,aviation,upper_air,auto_type,office_type,country
0,AB,ABEE AGDM,CXAF,NaN,7128.0,54 17,112 58W,664,Yes,NaN,NaN,NaN,NaN,NaN,CA
1,AB,ANDREW AGDM,CXAG,NaN,7128.0,53 55,112 17W,625,Yes,NaN,NaN,NaN,NaN,NaN,CA
2,AB,ATMORE AGDM,CXAJ,NaN,7128.0,54 46,112 49W,574,Yes,NaN,NaN,NaN,NaN,NaN,CA
3,AB,BANFF (MARS),CWZG,WZG,NaN,51 12,115 32W,397,Yes,NaN,NaN,NaN,NaN,NaN,CA
4,AB,BARNWELL AGDM,CXBW,NaN,7134.0,49 48,112 18W,824,Yes,NaN,NaN,NaN,NaN,NaN,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
832,YT,TESLIN (MARS),CWZW,WZW,NaN,60 10,132 44W,705,Yes,NaN,NaN,NaN,NaN,NaN,CA
833,YT,TESLIN ARPT (AUT,CYZW,YZW,7104.0,60 10,132 45W,705,Yes,NaN,TAF,NaN,NaN,NaN,CA
834,YT,WATSON LAKE AIRP,CYQH,YQH,7195.0,60 07,128 49W,690,Yes,NaN,TAF,NaN,NaN,NaN,CA
835,YT,WATSON LAKE,CXQH,NaN,7119.0,60 07,128 49W,690,Yes,NaN,NaN,NaN,NaN,NaN,CA
836,YT,WHITEHORSE AIRPO,CYXY,YXY,7196.0,60 43,135 04W,703,Yes,NaN,TAF,Rawinsonde,NaN,NaN,CA

,province,station_name,icao,iata,synop,latitude,longitude,elevation_m,metar,nexrad,aviation,upper_air,auto_type,office_type,country
11,AB,CALGARY INTNL AR,CYYC,YYC,7187.0,51 07,114 01W,84,Yes,NaN,TAF,NaN,NaN,NaN,CA
13,AB,CALGARY/SPRINGBA,CYBW,YBW,7186.0,51 06,114 22W,200,Yes,NaN,TAF,NaN,NaN,NaN,CA
18,AB,COLD LAKE (CAN,CYOD,YOD,7112.0,54 24,110 17W,544,Yes,NaN,TAF,Military,NaN,NaN,CA
25,AB,EDMONTON INTL AR,CYEG,YEG,7112.0,53 17,113 34W,723,Yes,NaN,TAF,NaN,NaN,NaN,CA
28,AB,EDMONTON MUNICIP,CYXD,YXD,7187.0,53 34,113 31W,671,Yes,NaN,TAF,NaN,NaN,NaN,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
828,YT,MAYO AIRPORT,CYMA,NaN,7196.0,63 37,135 52W,504,Yes,NaN,TAF,NaN,NaN,NaN,CA
829,YT,OLD CROW AIRPORT,CYOC,YOC,NaN,67 34,139 49W,251,Yes,NaN,TAF,NaN,NaN,NaN,CA
833,YT,TESLIN ARPT (AUT,CYZW,YZW,7104.0,60 10,132 45W,705,Yes,NaN,TAF,NaN,NaN,NaN,CA
834,YT,WATSON LAKE AIRP,CYQH,YQH,7195.0,60 07,128 49W,690,Yes,NaN,TAF,NaN,NaN,NaN,CA
836,YT,WHITEHORSE AIRPO,CYXY,YXY,7196.0,60 43,135 04W,703,Yes,NaN,TAF,Rawinsonde,NaN,NaN,CA

In [11]:
station_list = available_stations_df['icao'].tolist()
print(station_list)

['CYYC', 'CYBW', 'CYOD', 'CYEG', 'CYXD', 'CYED', 'CZVL', 'CYPY', 'CYMM', 'CYQU', 'CYOJ', 'CYQL', 'CYLL', 'CYXH', 'CYPE', 'CYQF', 'CYZH', 'CYZU', 'CYXX', 'CBBC', 'CYBL', 'CYCG', 'CYQQ', 'CYXC', 'CYDQ', 'CYDL', 'CYYE', 'CYXJ', 'CYKA', 'CYLW', 'CYZY', 'CZMT', 'CYCD', 'CYYF', 'CYZT', 'CYXS', 'CYPR', 'CYDC', 'CYQZ', 'CYZP', 'CYYD', 'CYXT', 'CYAZ', 'CYVR', 'CYWH', 'CYYJ', 'CYWL', 'CYBR', 'CYYQ', 'CYDN', 'CYGX', 'CYIV', 'CYYL', 'CYPG', 'CYQD', 'CYTH', 'CYWG', 'CYNE', 'CZBF', 'CYFC', 'CYCX', 'CACQ', 'CYQM', 'CYSJ', 'CYSL', 'CYCA', 'CZUM', 'CYDF', 'CYQX', 'CYYR', 'CWWU', 'CYMH', 'CYDP', 'CYAY', 'CYYT', 'CYJT', 'CYWK', 'CYZX', 'CYHZ', 'CWSA', 'CYSA', 'CYAW', 'CYQY', 'CYQI', 'CYOA', 'CYWJ', 'CYGH', 'CZFM', 'CYFS', 'CYSM', 'CYHY', 'CYHI', 'CYEV', 'CYLK', 'CYVQ', 'CYPC', 'CYRA', 'CYSY', 'CYUB', 'CYWE', 'CYZF', 'CYLT', 'CYAB', 'CYEK', 'CYBK', 'CYVM', 'CYCB', 'CYTE', 'CYCO', 'CYZS', 'CYCY', 'CYEU', 'CYFB', 'CYHK', 'CYUX', 'CYGT', 'CYWO', 'CYSR', 'CYXP', 'CYBB', 'CYIO', 'CYRT', 'CYUT', 'CYRB', 'CYYH', 'CYTL', 'CYBN', 'CYLD', 'CYHD', 'CYXR', 'CYEL', 'CYGQ', 'CYZE', 'CYHM', 'CYYU', 'CYQK', 'CYGK', 'CWSN', 'CYXU', 'CYSP', 'CYMO', 'CYQA', 'CYYB', 'CYOW', 'CYWA', 'CYPQ', 'CYPL', 'CYRL', 'CYZR', 'CYAM', 'CYXL', 'CYSN', 'CYSB', 'CYTJ', 'CYQT', 'CYTS', 'CYKZ', 'CYTZ', 'CYYZ', 'CYTR', 'CYKF', 'CYXZ', 'CYVV', 'CYQG', 'CYYG', 'CYBG', 'CYBC', 'CYBX', 'CYMT', 'CYGP', 'CYND', 'CYGV', 'CYGR', 'CYPH', 'CYIK', 'CYVP', 'CYGW', 'CYAH', 'CYGL', 'CYYY', 'CYUL', 'CYMX', 'CYNA', 'CYPX', 'CYHA', 'CYQB', 'CYRJ', 'CYUY', 'CYHU', 'CYKL', 'CYZV', 'CYSC', 'CYTQ', 'CYRQ', 'CYVO', 'CYOY', 'CYKQ', 'CYVT', 'CWVP', 'CYEN', 'CYKJ', 'CYVC', 'CYMJ', 'CYQW', 'CYPA', 'CYQR', 'CYXE', 'CYSF', 'CYYN', 'CYQV', 'CYDB', 'CYDA', 'CZFA', 'CYMA', 'CYOC', 'CYZW', 'CYQH', 'CYXY']